apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: '{{.Values.microservices.orderService.serviceName}}'
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.microservices.orderService.serviceName}}'
  updatePolicy:
    updateMode: Auto
