apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: '{{.Values.microservices.orderService.serviceName}}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.microservices.orderService.serviceName}}'
  minReplicas: '{{.Values.microservices.orderService.minReplicas}}'
  maxReplicas: '{{.Values.microservices.orderService.maxReplicas}}'
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
